name: Tests Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  django_test_args: '-Wa'

jobs:
  build:
    name: Tests Pipeline (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.13]
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: 'secret'
          MYSQL_DATABASE: 'boilerplate'
          MYSQL_USER: 'user'
          MYSQL_PASSWORD: 'secret'
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v7
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: pip install --no-input -vqr requirements.txt
      - name: Create environment file
        run: |
          cp .env.example .env
          sed -i "s/APP_ENV=local/APP_ENV=test/g" .env
          sed -i "s/CONNECTION=sqlite/CONNECTION=mysql/g" .env
          sed -i "s/MARIADB_USER=root/MARIADB_USER=user/g" .env
          sed -i "s/MARIADB_PASSWORD=/MARIADB_PASSWORD=secret/g" .env
          sed -i "s/MARIADB_PORT=3306/MARIADB_PORT=${{ job.services.mysql.ports['3306'] }}/g" .env
      - name: Grant test database privileges
        run: |
          mysql --host=127.0.0.1 --port=${{ job.services.mysql.ports['3306'] }} -uroot -psecret -e \
            "GRANT ALL PRIVILEGES ON \`test_%\`.* TO 'user'@'%'; FLUSH PRIVILEGES;"
      - name: Run Migrations
        run: python manage.py migrate --noinput
      - name: Run Seeder
        run: python manage.py seed
      - name: Run Tests
        run: |
          python ${{ env.django_test_args }} manage.py test
